/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashRouteImport } from './routes/_dash'
import { Route as DashIndexRouteImport } from './routes/_dash.index'
import { Route as DashResearchRouteImport } from './routes/_dash.research'
import { Route as DashPlannerRouteImport } from './routes/_dash.planner'
import { Route as DashNotesRouteImport } from './routes/_dash.notes'
import { Route as DashEmailRouteImport } from './routes/_dash.email'

const DashRoute = DashRouteImport.update({
  id: '/_dash',
  getParentRoute: () => rootRouteImport,
} as any)
const DashIndexRoute = DashIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashRoute,
} as any)
const DashResearchRoute = DashResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => DashRoute,
} as any)
const DashPlannerRoute = DashPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => DashRoute,
} as any)
const DashNotesRoute = DashNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => DashRoute,
} as any)
const DashEmailRoute = DashEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => DashRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashIndexRoute
  '/email': typeof DashEmailRoute
  '/notes': typeof DashNotesRoute
  '/planner': typeof DashPlannerRoute
  '/research': typeof DashResearchRoute
}
export interface FileRoutesByTo {
  '/email': typeof DashEmailRoute
  '/notes': typeof DashNotesRoute
  '/planner': typeof DashPlannerRoute
  '/research': typeof DashResearchRoute
  '/': typeof DashIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dash': typeof DashRouteWithChildren
  '/_dash/email': typeof DashEmailRoute
  '/_dash/notes': typeof DashNotesRoute
  '/_dash/planner': typeof DashPlannerRoute
  '/_dash/research': typeof DashResearchRoute
  '/_dash/': typeof DashIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/email' | '/notes' | '/planner' | '/research'
  fileRoutesByTo: FileRoutesByTo
  to: '/email' | '/notes' | '/planner' | '/research' | '/'
  id:
    | '__root__'
    | '/_dash'
    | '/_dash/email'
    | '/_dash/notes'
    | '/_dash/planner'
    | '/_dash/research'
    | '/_dash/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashRoute: typeof DashRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dash': {
      id: '/_dash'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash/': {
      id: '/_dash/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/research': {
      id: '/_dash/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof DashResearchRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/planner': {
      id: '/_dash/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof DashPlannerRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/notes': {
      id: '/_dash/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof DashNotesRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/email': {
      id: '/_dash/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof DashEmailRouteImport
      parentRoute: typeof DashRoute
    }
  }
}

interface DashRouteChildren {
  DashEmailRoute: typeof DashEmailRoute
  DashNotesRoute: typeof DashNotesRoute
  DashPlannerRoute: typeof DashPlannerRoute
  DashResearchRoute: typeof DashResearchRoute
  DashIndexRoute: typeof DashIndexRoute
}

const DashRouteChildren: DashRouteChildren = {
  DashEmailRoute: DashEmailRoute,
  DashNotesRoute: DashNotesRoute,
  DashPlannerRoute: DashPlannerRoute,
  DashResearchRoute: DashResearchRoute,
  DashIndexRoute: DashIndexRoute,
}

const DashRouteWithChildren = DashRoute._addFileChildren(DashRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DashRoute: DashRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
